air_boltic:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: admin
      port: 5432
      schema: analytics
      threads: 1
      type: postgres
      user: admin
  target: dev
